name: Continuous integration

on:
  # Manual dispatch for testing
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Build construo
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
          build-root-directory: construo
      - name: Build test project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Check code formatting construo
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessCheck
          build-root-directory: construo
      - name: Check code formatting test project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessCheck
